name:  raja workflows
 
on:
  push:
    branches:
      - main
    pull_request:
      branches:
        - main
    jobs:
      raja_job:
    runs-on: ubuntu-latest
    steps:
      - name: clone another repository
        run: |
              git clone  https://github.com/rajagaurdevops/GitHub_Action_Learn.git
              ls
              cat README     